# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: sunjiahao
    password: 123456
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000ms
  aop:
    proxy-target-class: true
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.108.189.207:8848
        ip: 42.193.20.2

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.apache.ibatis: warn


server:
  address: 0.0.0.0
  port: 8083
  active:
    env: dev
